language:
  - lang: Rust
    ext:
      - rs
    ignore: []

  - lang: Go
    ext:
      - go
    ignore: []

  - lang: JSX
    ext:
      - jsx
    ignore:
      - dist
      - out

  - lang: TypeScript
    ext:
      - ts
      - tsx
      - mts
      - cts
    ignore:
      - dist
      - out
      - .next

  - lang: Vue
    ext:
      - vue
    ignore:
      - .nuxt

common:
  ignore:
    - .git
    - node_modules
    - target
