name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Release binary
    env:
      ARTIFACT_NAME: languatage
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: ${{ env.ARTIFACT_NAME }}
            asset_name: ${{ env.ARTIFACT_NAME }}-x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: ${{ env.ARTIFACT_NAME }}
            asset_name: ${{ env.ARTIFACT_NAME }}-x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            artifact_name: ${{ env.ARTIFACT_NAME }}.exe
            asset_name: ${{ env.ARTIFACT_NAME }}-x86_64-pc-windows-gnu.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: ${{ env.ARTIFACT_NAME }}
            asset_name: ${{ env.ARTIFACT_NAME }}-x86_64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Cross build with all features
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }} --all-features --verbose

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
